---
version: "2"
services:
  
# WebServer-A
  webserver-a:
    image: "mayankt/webserver:a"
    restart: always
    networks:
      sandbox:
        ipv4_address: "192.168.13.11"
    hostname: webserver-a

# WebServer-B
  webserver-b:
    image: "mayankt/webserver:b"
    restart: always
    networks:
      sandbox:
        ipv4_address: "192.168.13.12"
    hostname: webserver-b

# NetScalet CPX
  cpx:
    image: "mayankt/cpx:12.0-41.16"
    restart: always
    networks:
      sandbox:
        ipv4_address: "192.168.13.20"
    environment:
    - EULA=yes
    privileged: true
    # Open ports on host to expose for NetScaler functionality testing. 
    ports:
      - "10000-10050:10000-10050"
    hostname: cpx

# IDE Environment 
  nitro-ide:
    image: "mayankt/nitro-ide"
    restart: always
    networks:
      sandbox:
        ipv4_address: "192.168.13.10"
    ports:
      - "9090:80"
      - "9091:8000"
# Uncomment the next two lines to map to your local host directory where your git projects are stored to share persistence data with IDE.
#    volumes:
#        - /Gihub-proj:/workspace:rw      
    hostname: nitro-ide

networks:
  # defined sandbox network for docker containers
  sandbox:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.13.0/24"